import 'package:flutter/material.dart';

import '../helpers/helprodu.dart';

class CategoryTwo {
  final int? idc, idsub;
  final String name;
  final String? icon, imgtab;
  final List<String> itemsss;

  CategoryTwo({
    required this.idc,
    required this.idsub,
    required this.name,
    this.icon,
    this.imgtab,
    required this.itemsss,
  });
}

final List<CategoryTwo> categorythree = [
    CategoryTwo(
      idc: 1,
      idsub: 1,
      name: "Licores",
      icon: "assets/icons/licor.svg",
      imgtab: "assets/images/images-licores.png",
      itemsss: ['Vino', 'Cerveza', 'Aguardiente', 'Ron', 'Wisky', 'Vodka']),
  CategoryTwo(
      idc: 2,
      idsub: 1,
      name: "Bebidas",
      icon: "assets/icons/shirt.svg",
      imgtab: "assets/images/medium_1.png",
      itemsss: [
        'Agua',
        'Gaseosa',
        'Jugos',
        'Energizantes',
        'Saborizada',
        'Hidratantes'
      ]),
  CategoryTwo(
      idc: 3,
      idsub: 1,
      name: "Lacteos",
      icon: "assets/icons/pants.svg",
      imgtab: "assets/images/medium_2.png",
      itemsss: ['Leche', 'Queso', 'Yogurt', 'Kumis', 'Huevos', 'Mantequilla']),
  CategoryTwo(
      idc: 4,
      idsub: 1,
      name: "Frutas",
      icon: "assets/icons/Tshirt.svg",
      imgtab: "assets/images/medium_3.png",
      itemsss: ['Manzana', 'Banano', 'Pera', 'Maracuya', 'Guayaba', 'Mango']),
];

class Product {
  final int? id;
  final String image, title;
  final int? categoryId, subcategoryId;
  final int price;
  final int? price_1, price_2, price_3, price_4, price_5;
  final Color? bgColor;
  bool isFavorated;

  Product({
    this.id,
    required this.isFavorated,
    required this.image,
    required this.title,
    required this.categoryId,
    required this.subcategoryId,
    required this.price,
    this.price_1,
    this.price_2,
    this.price_3,
    this.price_4,
    this.price_5,
    this.bgColor = const Color(0xFFEFEFF2),
  });
}

List<Product> demoproduct = [
  Product(
    id: HelProdu.toInt(1),
    image: "assets/images/product_0.png",
    title: "Shampoo Savital",
    price: 16500,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 2,
    subcategoryId: 1,
    bgColor: const Color(0xFFFEFBF9),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(2),
    image: "assets/images/product_1.png",
    title: "Shampoo HS",
    price: 23000,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 2,
    subcategoryId: 1,
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(3),
    image: "assets/images/product_1.png",
    title: "Shampoo Sedal",
    price: 18000,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 2,
    subcategoryId: 1,
    bgColor: const Color(0xFFF8FEFB),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(4),
    image: "assets/images/product_99.png",
    title: "Shampoo Konzil",
    price: 14900,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 2,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(5),
    image: "assets/images/product_60.png",
    title: "Ron Viejo de Caldas",
    price: 48700,
    price_1: 48700,
    price_2: 50000,
    price_3: 55900,
    price_4: 53500,
    price_5: 51000,
    categoryId: 1,
    subcategoryId: 4,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(6),
    image: "assets/images/product_61.png",
    title: "Vino Cariñoso",
    price: 22000,
    price_1: 19000,
    price_2: 21000,
    price_3: 19900,
    price_4: 21400,
    price_5: 19900,
    categoryId: 1,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(7),
    image: "assets/images/gallo-rosado.png",
    title: "Vino rosado Gallo",
    price: 39900,
    price_1: 41000,
    price_2: 43000,
    price_3: 45000,
    price_4: 42500,
    price_5: 41000,
    categoryId: 1,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(8),
    image: "assets/images/doble-anis.png",
    title: "Aguardiente Doble Anis",
    price: 21500,
    price_1: 22000,
    price_2: 25000,
    price_3: 23200,
    price_4: 24100,
    price_5: 22000,
    categoryId: 1,
    subcategoryId: 3,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(9),
    image: "assets/images/poker-cerveza.png",
    title: "Poker",
    price: 14900,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(10),
    image: "assets/images/aguila-cerveza.png",
    title: "Aguila",
    price: 14900,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(11),
    image: "assets/images/product_11.png",
    title: "Costeña",
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    price: 14900,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(12),
    image: "assets/images/product_67.png",
    title: "Red Bull",
    price_1: 5800,
    price_2: 6500,
    price_3: 5900,
    price_4: 6300,
    price_5: 6300,
    price: 6000,
    categoryId: 3,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(13),
    image: "assets/images/aguila-cerveza.png",
    title: "Aguila Light",
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    price: 14900,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(14),
    image: "assets/images/product_63.png",
    title: "Vino Carmen",
    price_1: 39900,
    price_2: 38900,
    price_3: 42000,
    price_4: 41700,
    price_5: 41000,
    price: 38900,
    categoryId: 1,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(15),
    image: "assets/images/product_64.png",
    title: "Vino Santa Carolina",
    price_1: 48200,
    price_2: 50900,
    price_3: 52000,
    price_4: 53000,
    price_5: 51000,
    price: 46000,
    categoryId: 1,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(16),
    image: "assets/images/product_65.png",
    title: "Speed Max",
    price_1: 1500,
    price_2: 1700,
    price_3: 1500,
    price_4: 1500,
    price_5: 1500,
    price: 1490,
    categoryId: 3,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(17),
    image: "assets/images/product_66.png",
    title: "Vive cien",
    price_1: 2300,
    price_2: 3000,
    price_3: 2500,
    price_4: 2500,
    price_5: 2500,
    price: 2490,
    categoryId: 3,
    subcategoryId: 1,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(18),
    image: "assets/images/product_18.png",
    title: "Club Colombia",
    price_1: 4700,
    price_2: 5700,
    price_3: 5100,
    price_4: 5200,
    price_5: 5200,
    price: 4900,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(19),
    image: "assets/images/havana.png",
    title: "Ron havana",
    price: 64900,
    price_1: 68000,
    price_2: 69000,
    price_3: 70000,
    price_4: 70000,
    price_5: 69000,
    categoryId: 1,
    subcategoryId: 4,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(20),
    image: "assets/images/product_20.png",
    title: "Corona Extra",
    price: 14900,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(21),
    image: "assets/images/product_5.png",
    title: "Heineken",
    price: 14900,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(22),
    image: "assets/images/149-BUD.png",
    title: "Budweiser",
    price: 14900,
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(23),
    image: "assets/images/640.png",
    title: "Andina",
    price_1: 17000,
    price_2: 17000,
    price_3: 17000,
    price_4: 17000,
    price_5: 17000,
    price: 14900,
    categoryId: 1,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(21),
    image: "assets/images/product_70.png",
    title: "Aguardiente Antioqueño",
    price: 26000,
    price_1: 25000,
    price_2: 26000,
    price_3: 27000,
    price_4: 25000,
    price_5: 27900,
    categoryId: 1,
    subcategoryId: 3,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(25),
    image: "assets/images/product_71.jpg",
    title: "Blanco Fiesta",
    price: 22900,
    price_1: 19500,
    price_2: 20000,
    price_3: 23000,
    price_4: 23400,
    price_5: 25000,
    categoryId: 1,
    subcategoryId: 3,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(26),
    image: "assets/images/product_72.png",
    title: "Ron Bacardí",
    price: 14900,
    price_1: 19500,
    price_2: 20000,
    price_3: 23000,
    price_4: 23400,
    price_5: 25000,
    categoryId: 1,
    subcategoryId: 4,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(27),
    image: "assets/images/product_73.png",
    title: "Ron Barcelo Añejo",
    price: 87900,
    price_1: 88000,
    price_2: 91900,
    price_3: 92000,
    price_4: 91500,
    price_5: 90900,
    categoryId: 1,
    subcategoryId: 4,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(28),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(7),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(29),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(30),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(31),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(32),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(33),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(34),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(35),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(36),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(37),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(38),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(39),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(40),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(41),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(42),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(43),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(44),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(45),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(46),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(47),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(48),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(49),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(50),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(51),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(52),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(53),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(54),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(55),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(56),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(57),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(58),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(59),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(60),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(61),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(62),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(63),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(64),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(65),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(66),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(67),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(68),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(69),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(70),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(71),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(72),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(73),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(74),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(75),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(76),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(77),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(78),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(79),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(80),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(81),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(82),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(83),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(84),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(85),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(86),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(87),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(88),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(89),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(90),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(91),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(92),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(93),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(94),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
  Product(
    id: HelProdu.toInt(95),
    image: "assets/images/product_1.png",
    title: "Shampoo Konzil",
    price: 14900,
    categoryId: 4,
    subcategoryId: 2,
    bgColor: const Color(0xFFEEEEED),
    isFavorated: false,
  ),
];

